modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "timecapsules"
version = "${version}"
displayName = "Timecapsules"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.timecapsules]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.timecapsules]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.timecapsules]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "timecapsules.mixins.json"
